// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAva39AAAC3OGCtmT7EJOS9FSetAKVpZ_I',
    appId: '1:1082700149503:web:2e037da84acc378ae812ca',
    messagingSenderId: '1082700149503',
    projectId: 'noteapp52',
    authDomain: 'noteapp52.firebaseapp.com',
    storageBucket: 'noteapp52.appspot.com',
    measurementId: 'G-8CSYJ66HJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx_HKh_gAJPj5NHP1xzHGvcpdRJrzaPfA',
    appId: '1:1082700149503:android:a26d2f621ce4a3fae812ca',
    messagingSenderId: '1082700149503',
    projectId: 'noteapp52',
    storageBucket: 'noteapp52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_-6ppyNZiqnyW3H0kUrGQ9x7gjsHdTqA',
    appId: '1:1082700149503:ios:d28c8d0d8a9020c6e812ca',
    messagingSenderId: '1082700149503',
    projectId: 'noteapp52',
    storageBucket: 'noteapp52.appspot.com',
    iosBundleId: 'com.example.noteApp52',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_-6ppyNZiqnyW3H0kUrGQ9x7gjsHdTqA',
    appId: '1:1082700149503:ios:9013e5defd289567e812ca',
    messagingSenderId: '1082700149503',
    projectId: 'noteapp52',
    storageBucket: 'noteapp52.appspot.com',
    iosBundleId: 'com.example.noteApp52.RunnerTests',
  );
}
